name: Docker Image CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        if: github.event_name != 'pull_request'
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        if: github.event_name == 'pull_request'
        run: |
          echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF})" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
      -
        uses: actions/setup-python@master
        with:
          python-version: 3.9.x
          architecture: x64
      -
        name: Install dependencies
        run: |
          python3 -m pip install --no-cache-dir pipenv;
          pipenv install --system --dev --pre;
      -
        name: Build the package's binary distribution
        id: create_release_artifact
        run: |
          make release-artifact;
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ steps.create_release_artifact.package_version }}
          push: true
          tags: |
            ${{ github.repository }}:${{ env.BRANCH_NAME }}
            ${{ github.repository }}:${{ env.BRANCH_NAME }}-${{ env.SHA_SHORT }}
